# Generated by Django 2.2.5 on 2019-09-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onjeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signIn',
            new_name='customer',
        ),
    ]
