# Generated by Django 2.2.5 on 2019-09-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onjeapp', '0002_auto_20190911_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Full name')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=12.99, max_digits=20)),
                ('zip_code', models.CharField(max_length=10, verbose_name='ZIP/ Postal Code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
            ],
        ),
    ]
