# Generated by Django 2.2.5 on 2019-09-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onjeapp', '0003_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='contact',
        ),
    ]
