# Generated by Django 2.2.5 on 2019-09-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onjeapp', '0004_auto_20190912_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address1',
            field=models.CharField(default='Address line1', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address2',
            field=models.CharField(default='Address line2', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='City', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(default='ZIP/ Postal Code', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15.99, max_digits=20),
        ),
    ]
